"""create_student_winner_table

Revision ID: 300f310194e7
Revises: 7a6d54f9a20c
Create Date: 2022-12-26 11:23:25.829272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300f310194e7'
down_revision = '7a6d54f9a20c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_points', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quarter_range_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prize_id'], ['prizes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quarter_range_id'], ['quarter-ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_winners')
    # ### end Alembic commands ###
