"""remove-quarter-studentPoint

Revision ID: 32fc4f97fb75
Revises: fcf380d29bd0
Create Date: 2023-01-15 11:20:18.897466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fc4f97fb75'
down_revision = 'fcf380d29bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_points_quarter_range_id_fkey', 'student_points', type_='foreignkey')
    op.drop_column('student_points', 'quarter_range_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_points', sa.Column('quarter_range_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('student_points_quarter_range_id_fkey', 'student_points', 'quarter-ranges', ['quarter_range_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
