"""define-quarter-tables

Revision ID: 50829c2ded03
Revises: ca2ff2cbd683
Create Date: 2022-12-23 17:39:39.446864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50829c2ded03'
down_revision = 'ca2ff2cbd683'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter')
    )
    op.create_table('quarter-ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_range', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_range', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quarter-ranges')
    op.drop_table('quarters')
    # ### end Alembic commands ###
