"""add-quarterRange-eventTime

Revision ID: 59b5743011e4
Revises: 32fc4f97fb75
Create Date: 2023-01-15 11:57:38.968584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b5743011e4'
down_revision = '32fc4f97fb75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_times', sa.Column('quarter_range_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_times', 'quarter-ranges', ['quarter_range_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_times', type_='foreignkey')
    op.drop_column('event_times', 'quarter_range_id')
    # ### end Alembic commands ###
