"""update-student-point-event-time

Revision ID: 64c93355a306
Revises: 5c9449fabb0d
Create Date: 2023-01-15 10:36:47.531335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c93355a306'
down_revision = '5c9449fabb0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_points', sa.Column('event_time_id', sa.Integer(), nullable=False))
    op.drop_constraint('student_points_event_id_fkey', 'student_points', type_='foreignkey')
    op.create_foreign_key(None, 'student_points', 'event_times', ['event_time_id'], ['id'], ondelete='CASCADE')
    op.drop_column('student_points', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_points', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_points', type_='foreignkey')
    op.create_foreign_key('student_points_event_id_fkey', 'student_points', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('student_points', 'event_time_id')
    # ### end Alembic commands ###
