"""add-access-date-column-userStep

Revision ID: 9c8bf2b541e3
Revises: 0758d1380373
Create Date: 2023-01-29 14:26:57.506399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8bf2b541e3'
down_revision = '0758d1380373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_steps', sa.Column('accessed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_steps', 'accessed_at')
    # ### end Alembic commands ###
