"""add-grade-level-to-user

Revision ID: ca2ff2cbd683
Revises: a182d522542b
Create Date: 2022-12-23 17:22:50.056336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2ff2cbd683'
down_revision = 'a182d522542b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###
