"""remove-attendedTime-studentPoint

Revision ID: fcf380d29bd0
Revises: 64c93355a306
Create Date: 2023-01-15 10:43:26.910228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf380d29bd0'
down_revision = '64c93355a306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_points', 'attended_at')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_points', sa.Column('attended_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    pass
    # ### end Alembic commands ###
